# Labs week 2

Students:
* Daniyar Kurmanbayev
* Purvi Jain
* Rishabh Radhakrishnan
* Vrinda Parameswaran

### Exercise 1:
1. Using numpy arrays and slicing operations (:), define and print the following A, B, and C matrix:

In [20]:
import numpy as np

In [21]:
A = np.array([[5, 2, 3],
              [6, 1, 3],
              [2, 4, 1]])

B = np.array([[5, 2, 3],
              [6, 1, 3],
              [2, 4, 1]])

C = np.array([[5, 2, 3],
              [6, 1, 3],
              [2, 4, 1]])

A, B , C

(array([[5, 2, 3],
        [6, 1, 3],
        [2, 4, 1]]),
 array([[5, 2, 3],
        [6, 1, 3],
        [2, 4, 1]]),
 array([[5, 2, 3],
        [6, 1, 3],
        [2, 4, 1]]))

2. Define D matrix using numpy:

In [22]:
D = np.array([[4, -7, 4],
              [5, 6, -1],
              [-4, 2, 5]])

D

array([[ 4, -7,  4],
       [ 5,  6, -1],
       [-4,  2,  5]])

3. Use numpy matmul to calculate AD and also DA. Are they equal?

In [23]:
AD = np.matmul(A, D)
AD

array([[ 18, -17,  33],
       [ 17, -30,  38],
       [ 24,  12,   9]])

In [24]:
DA = np.matmul(D, A)
DA

array([[-14,  17,  -5],
       [ 59,  12,  32],
       [  2,  14,  -1]])

In [25]:
is_equal = not (AD == DA).__contains__(False)
print(f'AD is {"" if is_equal else "not"} equal to DA')

AD is not equal to DA


4. Manually calculate the determinant and inverse of B. Use numpy to calculate the same entities and confirm that your manual calculation agrees with your results from the jupyter notebook.

In [26]:
B

array([[5, 2, 3],
       [6, 1, 3],
       [2, 4, 1]])

In [27]:
M11 = (1 * 1) - (3 * 4)
M12 = (6 * 1) - (3 * 2)
M13 = (6 * 4) - (1 * 2)
M21 = (2 * 1) - (3 * 4)
M22 = (5 * 1) - (3 * 2)
M23 = (5 * 4) - (2 * 2)
M31 = (2 * 3) - (3 * 1)
M32 = (5 * 3) - (3 * 6)
M33 = (5 * 1) - (2 * 6)

In [28]:
my_determinant = (5 * M11) - (2 * M12) + (3 * M13)
my_determinant

11

In [29]:
cofactors_matrix=[[M11,-M12,M13],
                 [-M21,M22,-M23],
                  [M31,-M32,M33]]
cofactors_matrix

[[-11, 0, 22], [10, -1, -16], [3, 3, -7]]

In [30]:
adjugate_matrix=[[M11,-M21,M31],
                [-M12,M22,-M32],
                [M13,-M23,M33]]
adjugate_mat=np.array(adjugate_matrix)
adjugate_mat

array([[-11,  10,   3],
       [  0,  -1,   3],
       [ 22, -16,  -7]])

In [31]:
B_inverse_matrix=(1/my_determinant)*adjugate_mat
B_inverse_matrix

array([[-1.        ,  0.90909091,  0.27272727],
       [ 0.        , -0.09090909,  0.27272727],
       [ 2.        , -1.45454545, -0.63636364]])

In [32]:
np_determinant = np.linalg.det(B)
np_determinant

11.000000000000002

In [33]:
np_inverse = np.linalg.inv(B)
np_inverse

array([[-1.        ,  0.90909091,  0.27272727],
       [ 0.        , -0.09090909,  0.27272727],
       [ 2.        , -1.45454545, -0.63636364]])

In [34]:
# Manual calculated B Inverse agrees with the results from the jupyter notebook.

5. Use numpy to calculate the inverse of D. Confirm that 〖DD〗^(-1) and D^(-1) D both are 3-by-3 identity matrices. Do you have any observations?

In [35]:
D_inverse = np.linalg.inv(D)
DDi = D * D_inverse
DiD = D_inverse * D

DDi == DiD

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Exercise 2:
1. Calculate the bag of words (without TF-IDF, just word counts) matrix for the following 5 phrases:
    * college student
    * airport taxi driver
    * Toronto art museum
    * life art
    * machine learning student

Hints: How many rows should be there? How many columns should be there?

In [36]:
def bag_of_words(sent, vocab_length, word_to_index):
    words = []
    rep = np.zeros(vocab_length)
    for w in sent:
        if w not in words:
            ind=word_to_index[w]
            rep[ind]+=1
            words.append(w)
    return rep

In [37]:
phrases = ['college student', 'airport taxi driver', 'Toronto art museum', 'life art', 'machine learning student']
words = {word.lower() for phrase in phrases for word in phrase.split(' ')}

bows = [[int(phrase.__contains__(word)) for word in words] for phrase in phrases]
bows

[[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0]]

2. Calculate the IDF for the words “college” and “art”.

In [38]:
phrases_college = [phrase.__contains__('college') for phrase in phrases].count(True)
IDF_college = np.log(len(phrases) / phrases_college)
IDF_college

1.6094379124341003

In [39]:
phrases_art = [phrase.__contains__('art') for phrase in phrases].count(True)
IDF_art = np.log(len(phrases) / phrases_art)
IDF_art


0.9162907318741551